{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf600
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\csgray\c0;}
\margl1440\margr1440\vieww28600\viewh18000\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs30 \cf2 \CocoaLigature0 ---\
- hosts: appserver\
  user: test\
  become: yes\
  become_method: sudo\
  tasks:\
\
  - name: 1. Install Latest Version HTTP/Apache RPMs\
    yum: name=httpd state=present\
\
  - name: 2. Start httpd service\
    service: name=httpd state=started enabled=yes\
\
  - name: 3. Copy the standard index.html file\
    copy: src=/home/test/index.html dest=/var/www/html/index.html mode=0664}